<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <title>Terms of Service - Islam Smart</title>
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
    <style>
        body {
            font-family: 'Arial', sans-serif; /* Your desired font */
            font-size: 14px; /* Your desired font size */
        }
    </style>
</head>
<body>

    <h1>Terms of Service for Islam Smart</h1>
    <p>Welcome to Islam Smart! These Terms of Service ("Terms") govern your access to and use of the Islam Smart app ("the App"). By using the App, you agree to comply with these Terms. If you do not agree, please do not use the App.</p>

    <h2>1. Use of the App</h2>
    <p>You agree to use Islam Smart in accordance with all applicable laws and regulations. You are solely responsible for any activity under your account and for maintaining the security of your login credentials.</p>
    <ul>
        <li>The App is designed for personal use only. You may not use the App for any unlawful or unauthorized purposes.</li>
    </ul>

    <h2>2. Account Registration and Unique ID</h2>
    <ul>
        <li>The App uses Google login to authenticate users. Upon login, a unique user ID will be generated based on your Google account.</li>
        <li>You acknowledge that no personal details such as your name, email address, or profile picture are collected. Only your unique Google ID is used to create a specific ID for Islam Smart.</li>
    </ul>

    <h2>3. Device-Specific Lifetime Purchases</h2>
    <p>The App offers products that are available for lifetime purchase but are tied to a single device.</p>
    <ul>
        <li><strong>Unique Device ID:</strong> When making a purchase, the App will generate a unique device ID using your device’s brand, model, and a random UUID (Universally Unique Identifier). Your purchase will be recorded and tied to this unique device ID.</li>
        <li><strong>Device Transfers:</strong> Lifetime purchases are restricted to a single device but can be transferred to another device upon verification. You must follow the proper procedures outlined within the App to transfer a purchase to a new device.</li>
    </ul>

    <h2>4. Network Failure and Local Data Storage</h2>
    <ul>
        <li>In the event of a network failure, some purchase records may be stored locally on your device until the App can update them to our servers.</li>
        <li><strong>Responsibility for Data Loss:</strong> If you uninstall the App or delete its data during a period when purchase records are stored locally due to network failure, Islam Smart is not responsible for any unsynchronized purchases lost as a result.</li>
    </ul>

    <h2>5. Refund Policy</h2>
    <p>All purchases made through the App are non-refundable, except where required by law or in cases of proven technical issues that prevent the delivery of the purchased service.</p>

    <h2>6. Location Services</h2>
    <p>Certain features of the App may require access to and use of your location data to provide services relevant to your region.</p>
    <ul>
        <li>By enabling location services, you consent to the use of location data to personalize your experience.</li>
        <li>Location data is stored locally on your device and is not shared with any third parties.</li>
    </ul>

    <h2>7. Limitation of Liability</h2>
    <p>To the maximum extent permitted by law, Islam Smart and its developers shall not be liable for any damages or losses, including but not limited to:</p>
    <ul>
        <li>Loss of unsynchronized purchases if you uninstall the App or delete its data during a network failure.</li>
        <li>Any unauthorized use of your account resulting from your failure to maintain the security of your login credentials.</li>
        <li>Inability to access or use the App due to network interruptions or other technical issues beyond our control.</li>
    </ul>

    <h2>8. User Responsibilities</h2>
    <ul>
        <li><strong>Account Security:</strong> You are responsible for maintaining the confidentiality of your Google login credentials and the unique ID generated by the App. You must notify us immediately of any unauthorized use of your account.</li>
        <li><strong>Device Data:</strong> You are responsible for managing your device’s data storage and ensuring that any local data, including purchase records, is properly synchronized when the network is available.</li>
    </ul>

    <h2>9. Modifications to the App and Terms</h2>
    <ul>
        <li>Islam Smart reserves the right to modify or discontinue the App, its features, or these Terms at any time, without notice.</li>
        <li>Any changes to the Terms will be posted within the App, and continued use of the App following such changes constitutes your acceptance of the new Terms.</li>
    </ul>

    <h2>10. Contact Us</h2>
    <p>If you have any questions or concerns regarding these Terms, or if you need assistance with purchases or account management, please contact us at <a href="mailto:subhi@zmq.in">subhi@zmq.in</a>.</p>

</body>
</html>
